name: CI

on: 
  push:
    branches:    
      - setup-pipeline 

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x]
    
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install Dependencies
      run: |
        yarn install
    
    - name: Run Tests
      run: |
        yarn test 
      env:
        CI: true
    
    - name: Build Project
      run: |
        yarn run build --if-present

    - name: Deploy to Vercel
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      run: |
        npm install -g vercel
        vercel --prod --token=$VERCEL_TOKEN --confirm --scope your-vercel-scope
