name: simple pipeline

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and Test
        run: |
          docker build -t my-ci-cd-image .
          docker run my-ci-cd-image
  testCases:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: clone repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          echo "Installing dependencies"
          npm install

      - name: Running test
        run: |
          echo "Running Test cases"
          npm run test

    env:
      CI: true
